### ISSUE TITLE
대한민국 정당과 국회 연대표

### ISSUE THREAD

**Issue by leejeonghoon** [jaryogujo/law-row#7]
updated: 160313
## 사전조사
- [x] 기존 디자인 자료 리서치
  - [주요정당변천사](https://www.dropbox.com/sh/57fiy77s9leq4m9/AAD62BA0jUMy7EcRxbekfDjca?dl=0)
- [x] [위키피디아 SVG 다운로드](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EB%AF%BC%EC%A3%BC%EB%8B%B9%EA%B3%84_%EC%A0%95%EB%8B%B9)
  - [선관위 자료](http://museum.nec.go.kr/vote/voteKorea2.do)와 비교
  - 선관위에 63년 이전 정보가 없음. 
- [x] 제작 목표 설정
  - 기존 자료 (조선일보, 경향신문 등)는 모두 위키피디아 자료와 형태를 베이스로 디자인.
  - 시간의 흐름을 세로로 나열하는 것이 직관적이지 못하고, 1945~2016년이 결코 짧은 기간이 아니기 때문에 확인하기 어려움.
  - & 최신이 가장 위에 있어도, 최신이 가장 아래에 있어도 부자연스러움.  
  - 스크롤로 내려보기는 좋지만 경향신문에서 제작한 [정당변천사 사례](http://www.khan.co.kr/election/choice2012/news/infographic.html)를 보면 알 수 있듯이 가로 600px정도의 사이즈에 정보를 잘 담지 못할꺼면 (어차피 크게 제작할꺼면) 세로 배열은 의미가 없음. 
  - 선관위 연표는 가로로 제작했지만 노트북 및 일반 데스크톱 PC의 모니터로 확인하기 어려운 사이즈. 
    - 벽에 크게 인쇄해서 붙여놓는 용도.
  - 자료구조 ver에서는 PC에서 확인할 수 있는 사이즈의 높이(800px~1080px)에 가로로 길어지는 형태로 만들 것.
  - 합당, 탈당 정보 및 언제 어떤 정당이 생겼고 없어졌는지 표현할 것.
- 자료
  - 1963~2016년 정당 등록 및 말소: [사이버선거역사관](http://museum.nec.go.kr/vote/voteKorea2.do)
  - [위키피디아- 대한민국의 민주당계 정당](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EB%AF%BC%EC%A3%BC%EB%8B%B9%EA%B3%84_%EC%A0%95%EB%8B%B9)
  - [대한민국의 시계열적 정당 지도 xlsx](https://ko.wikipedia.org/wiki/%ED%8C%8C%EC%9D%BC:Political_parties_of_south_korea.xls)
  - [대한민국의 진보정당](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EC%A7%84%EB%B3%B4%EC%A0%95%EB%8B%B9)
  - [대한민국의 역대 정당](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EC%97%AD%EB%8C%80_%EC%A0%95%EB%8B%B9)
## 표현 방법 고민
- 의석수
  - 의석수 표현 방법
  - 의석수 찾기
- 합당, 탈당의 역사
  - 기존 자료에서는 합당 탈당 정보를 확인하기 어려움.
  - 직선, 점선, 컬러 활용.
- 집권대통령 표시

**Comment by leejeonghoon** [comment]
1x 
https://www.dropbox.com/s/3eek8ifp9x8r7d6/-.png?dl=0
2x
https://www.dropbox.com/s/dhpq0464iyfs0s7/-%402x.png?dl=0

이미지 입니다. 
- 63~2015년 정당 등록, 말소일, 당대표 정보는 모두 넣었습니다.
- 1945~1962년 정보는 다른 다이어그램 이미지의 정당 정보, 위키피디아 등을 참고해서 삽입했는데 제대로 아카이브 해놓은 곳을 못찾겠네요.
- 존속기간 1개월 미만의 정당은 삽입하지 않았습니다. 
  - 스프레드 시트에는 자주색으로 표시해놨습니다.
- 범례
  - 다들 보수정당, 민주당계 정당, 진보정당 세가지로 나눠서 그렇게 나누긴 했는데 주요 정당들 제외하고 다른 정당들은 우선 회색으로 분류해놨습니다. 
  - 듣보 정당은 성향 구분을 확인하기 어렵기도하고 구분한다 하더라도 모두 컬러가 들어가면 주요 정당이 뭍혀버리니 회색으로 처리하는게 좋다고 생각하는데 범례 텍스트를 '기타,?'라고 적는 건 좀 아닌 것 같네요.
- 길이
  - 위에 작성한것처럼 600px정도로 만들 계획이었는데 대통령 및 국회 정보 삽입, 2000년대 이후 정당 정보가 너무 많아서 길이 조절에 실패했습니다. 
  - 좌측 하단 여백은 타이틀을 삽입했고요.
- 의석 수
  - 숫자 라벨, 컬러(명도 혹은 채도 변화)차이로 정보를 삽입하는 방법등을 이야기했었는데요.
  -  막대는 의회별이 아니라 등록일 말소일을 기준으로 삽입했던거라 예를들어 16대 국회시작일 열에 ㅇㅇ당 100석 이런 숫자를 넣기는 좀 어려울 것 같아요. 텍스트가 많아서 구분하기 어려울 것 같아요.
  - 명,채도 변화가 좀 더 가능성이 있겠지만 이건 몇개 샘플로 넣어보고 가능성을 확인해보겠습니다.
- todo (우선순위별)
  - 주요 정당 합당, 탈당 화살표 삽입
  - 정당 등록일 말소일 정당명, 당대표 정보 재확인
  - 기타 레이아웃 정리 (발행 가능)
  - 의석수 삽입
  - 1945-1963 정보 삽입

**Comment by leejeonghoon** [comment]
적합한 제목도 붙여야겠네요

**Comment by wonderino** [comment]
- 저번에 말한 것처럼 그냥 범례를 안 두는 것도 괜찮을 것 같아요
- 제목은 뭐하지... 정당 변천만 있는 건 아니니 흠 `대한민국 정당사`라고 많이 해두긴 했군요. `대한민국 정당과 국회`?

**Comment by wonderino** [comment]
타이틀 등등 세로쓰기는 어떨지요 폰트가 폰트인만큼 제안드려봅니다

**Comment by leejeonghoon** [comment]
@wonderino 사실 세로쓰기를 고려해서 만든 레이아웃인데 2000년대 이후가 너무 길어졌네요... T_T
![image](https://cloud.githubusercontent.com/assets/10662388/14431840/78e0ecf8-0042-11e6-9786-e9e27fe23171.png)
<지난주 작업화면>

의견 주신 세로쓰기 + 정당과 국회 + 범례x 적용해봤습니다.
[원본파일폴더](https://www.dropbox.com/sh/xd6ijdxwj3n9z6d/AAALrBO1J_uRPXxhk_A887Ita?dl=0)
![default](https://cloud.githubusercontent.com/assets/10662388/14436428/9ac6da66-0057-11e6-82cf-1bd56fe41ad6.jpg)
- 그밖에.. 오늘 [정당사연표](http://museum.nec.go.kr/vote/voteKorea2.do)확인하니 181~190이 추가되어있군요 -_- 국민의당은 위키 확인해서 넣었지만 나머지들은 주말까지 넣기 어려울듯합니다.

**Comment by wonderino** [comment]
- 시간이 없으니 181–190 추가는 국민의당 이외에는 무시하고 가지요 (총선 이후에 업데이트를 하는 방향으로)
- 오늘 저녁에 그냥 발행가능 할지요? @ghhan 도 한번 보면서 검토해주면 좋을듯

**Comment by leejeonghoon** [comment]
- 발행 타이밍은 놓쳤지만 코멘트 주시는 건 이어서 작업.

**Comment by leejeonghoon** [comment]
#### 작업 진행 공유
- 181~190추가, 전반적인 오류 수정, 10년단위 확인을 돕는 선 추가했습니다.
- 텍스트 컬러
  - 기존 그래픽에서 다뤘던 (나름 주요정당들) 정당들만 검정색으로 표시했고 나머지 정당은 모두 회색으로 표시했습니다.
- 막대 컬러
  - 이전 버전과 마찬가지로 범례가 있는건 아니지만 대통령 소속 정당, 총선 승리 정당을 표시하면 좋을 것 같아 색상을 넣어봤습니다.  
  - 1964년 ~ 1998년까지 민주당 계열의 대통령, 총선 승리가 없었지만, 3당합당 전후 계보를 표시하기위해 민주당계열에 컬러를 넣었습니다.
  - 정의당 계보는 현재 정의당 컬러를 삽입했습니다.

[원본링크](https://drive.google.com/open?id=0B3bUtA0__wXUTFZEYk9jWl83UDA)

**Comment by leejeonghoon** [comment]
커버 이미지
 ![image](https://cloud.githubusercontent.com/assets/10662388/14743356/2d278a86-08dc-11e6-989d-a80fc9560496.png)

집에오며 스케치한건데 ㅈㄹㄱㅈ 프로필 이미지와너무 흡사하군요.ㅋㅋ

**Comment by wonderino** [comment]
오호 저는 마음에 듭니다
디벨롭해주세요

**Comment by leejeonghoon** [comment]
![political_parties_of_south_korea 2x](https://cloud.githubusercontent.com/assets/10662388/15953863/f1451a38-2f0a-11e6-997f-ae1269d8bff9.jpg)
- [가장 최근 (160606) export](https://www.dropbox.com/sh/pxkq67e7fxlvfrj/AADxtXL93v_BuIT4ObVX5musa?dl=0)
- 좀 더 수정하고 싶은건 회색 막대중 글자가 검정색이 있고 회색이 있는데 >> `기존 그래픽에서 다뤘던 (나름 주요정당들) 정당들만 검정색으로 표시했고 나머지 정당은 모두 회색으로 표시.` 라고는 하지만 너무 모호하기 때문에 [대통령 임기, 국회 기간](https://docs.google.com/spreadsheets/d/1oOpRwU4IlL6gyMxMq8kw_dl2LDBsT9o0bssZW5cXs00/edit#gid=1006381912) 의 국회의원 배출 정당 (75개)만 검정으로 표시하고 나머지는 회색처리하면 좋을 것 같네요.

즉, 금뱃지 배출 정당명은 검정색 글씨 / 기타 정당은 회색 글씨

**Comment by leejeonghoon** [comment]
(아이디어가 떠올라 간단히 메모)
- 커버 그래픽디자인 욕심을 낸다면 이런 형태도 가능하겠군요.
  - 대한민국정당과국회
  - 정당과국회

![image](https://cloud.githubusercontent.com/assets/10662388/16072395/990f51ca-331b-11e6-93fc-ca8887f1d56a.png)

![image](https://cloud.githubusercontent.com/assets/10662388/16072404/ab2792fa-331b-11e6-95a2-650de4537177.png)

![image](https://cloud.githubusercontent.com/assets/10662388/16072436/ce2bf250-331b-11e6-93aa-0e2397f7f6ab.png)

**Comment by leejeonghoon** [comment]
63년 이후는 선관위 때문에 자료가 튼실한데 63 이전 자료는 중구난방이네요..
해산했다가 3년 후 다시 재결성 혹은 같은 이름으로 등장했으면 다른 정당인데 해산일이 후속 정당의 해산일로 되어있어서 하나하나 확인함.

『한국정당발달사』(이기하, 의회정치사, 1961)
『한국정당사』(한태수, 신태양사, 1961)
『대한민국정당사』 1(중앙선거관리위원회, 1973)
『해방30년사』 Ⅰ(송남헌, 성문각, 1976)
『한국현대정치사』(송남헌, 성문각, 1980)

이런 책들과 옛날 신문 기사를 좀 찾아봐야겠네요.

# 1~5대 국회(0석 배출 정당) 추가 및 수정
- [x] 서북청년회
  - 정당 아님. 삭제

# 1~5대 국회(1석 이상 배출 정당) 추가 및 수정

## 제헌국회
- [x] **한국독립당**
- [x] **단민당**
  - 자료 부족
- [x] **교육협회**
  - 자료 부족
- [x] **조선민주당**
- [x] **조선민족청년단**
- [x] **대한독립촉성노동총연맹**
- [x] **대한독립촉성농민총연맹**
  - 해산일 정확하지는 않음. (50년대 초)
- [x] **대동청년단**
  - 해산일 자료 없음
- [x] **대한독립촉성국민회**
  - 해산 연월일 찾는중
- [x] **한국민주당**
- [x] **대한청년단**

## 2대국회
- [x] **여자국민당**
- [x] **민주국민당**
- [x] **대한청년단**
- [ ] 사회당
  - 위키링크 없음
- [x] **대한독립촉성국민회**
  - 해산 연월일 찾는중
- [x] **일민구락부**
  - 해산 연월일 찾는중
- [x] 대한노동총연맹
  - 정당 아님, 위키자료 X
- [x] **대한부인회**
  - 자료 부족
- [ ] 민족자립연맹
  - 위키링크 없음.
- [x] **중앙불교위원회**
  - 자료 부족
- [x] 대한국민당

## 3대국회
- [x] **제헌국회의원동지회**
  - 자료 부족
- [x] **민주국민당**
- [x] **자유당**
- [x] **대한독립촉성국민회**
- [x] **대한국민당**

## 4대국회
- [x] **통일당**
- [x] **민주당**
- [x] 자유당

## 5대국회
- [x] **한국사회당**
- [x] **민주당**
- [x] 자유당
- [x] **헌정동지회**
  - 자료 x
- [x] **사회대중당**
- [x] 통일당

**Comment by leejeonghoon** [comment]
- [x]  [수정 및 업데이트 사항](https://www.dropbox.com/s/bemogb3f8q2u252/history-of-political-parties-kr.pdf?dl=0)
    - 19대 대통령 문재인 추가.
    - 2017년 2월 13일 새누리당에서 자유한국당으로 당명 변경.
    - 2017년 1월 24일 비박계 의원 29명 탈당 바른정당 창당.
    - 합당, 탈당 범례 추가
    - 박근혜 대통령 탄핵 소추안 가결 및 인용 날짜 추가 (2017.12.9 / 2017.3.10)
- [ ] 저장소 업데이트
